openapi: 3.0.0

info:
  title: Garnet API
  description: 'Garnet: a progress tracker'
  version: 1.0.0
  license:
    name: MIT
    url: https://github.com/alaindet/garnet/blob/main/LICENSE

servers:
  - url: http://localhost:8080/v1.0
    description: Development Server

paths:
  /tasks/{taskid}/as-student/{studentid}:
    put:
      summary: Lets a teacher move a task on a board as if being the board's owner
      parameters:
        - in: path
          name: taskid
          required: true
          schema:
            type: integer
        - in: path
          name: studentid
          schema:
            type: integer
      requestBody:
        required: true
        # TODO
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          content: application/json
